pipeline{
    agent any
    stages{
        stage("Building"){
            steps{
                sh 'python3 -m py_compile FirstPython.py'
                stash(name:"PythonResult", includes: "*.py*")
            }
        }
    }
}